### ISSUE TITLE
Note url aggregation in the plack middleware

### ISSUE THREAD

**Issue by colinnewell** [cv-library/NewFangle-Agent#9]
Because of the low level place the plack middleware hooks it tends to create lots of unique transactions rather than grouping things together as the code would be.  It would be good to acknowledge that in the docs and suggest some potential work arounds, or suggest that the transactions could be recorded using a different type of middleware with other frameworks that are more aware of the routing going on.

**Comment by jjatria** [comment]
Initially fixed with 75734d77d9763a. #10 might also contribute

**Comment by jjatria** [comment]
The fix was superseded by #11 and released in v0.005. We can now set a transaction name in the Plack environment under `newrelic.transaction_name`, and that will be set as the transaction name by the default transaction ender (if set).
